# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "fortran_rationals"
version = "0.1.0"
license = "MIT"
author = "Will Klausler"
maintainer = "wklausler@protonmail.com"
copyright = "Copyright 2026, Will Klausler"
description = ""
categories = [""]
keywords = ["fortran", "fortran-package-manager"]
homepage = "https://github.com/willklausler/fortran_rationals"

[features]
debug.gfortran.flags = "-g -Wall -fbacktrace -fcheck=all -Wextra -Wpedantic -Wuninitialized -Wmaybe-uninitialized -Wimplicit-interface -Wimplicit-procedure -Warray-temporaries -Wrealloc-lhs -finit-real=snan -finit-integer=-2147483648 -finit-logical=true -fstack-protector-all"
debug.gfortran.linux.flags = "-fsanitize=address,undefined"

debug.ifx.linux.flags = "-g -Wall -check all -warn all -traceback -fpe0 -init=snan,arrays -ftrapuv -fp-stack-check -diag-error-limit 10 -fsanitize=address,undefined"
debug.ifx.windows.flags = "/Zi /check:all /warn:all /traceback /fpe:0 /Qinit:snan,arrays /Qtrapuv"

debug.nvfortran.flags = "-g -Minform=inform -Mbounds -Mchkptr -Mchkstk -Mstandard -Ktrap=fp -traceback"

release.flags = "-O3"
release.gfortran.flags = "-fbacktrace -march=native -funroll-loops"
release.gfortran.linux.flags = "-flto"
release.ifx.linux.flags = "-xHost -unroll"
release.ifx.windows.flags = "/QxHost /Qunroll"

release.nvfortran.flags = "-Mrecursive -fast"

[profiles]
debug = ["debug"]
release = ["release"]